### ISSUE TITLE
Required for directory loading

### ISSUE THREAD

**Issue by bai-xuan** [erxson/Bruhfuscator#2]
Hi brother, because you commented out this code, I spent a day troubleshooting the problem that the jar class could not be loaded.
It is required and cannot be commented out. I have a problem when using the springboot jar package. Please be sure to test it.
Also, it cannot be commented, please modify it.

![image](https://github.com/erxson/Bruhfuscator/assets/38934025/595ddcca-0da8-4613-8d9f-5454c3f75254)

**Comment by bai-xuan** [comment]
Error details
![image](https://github.com/erxson/Bruhfuscator/assets/38934025/ed9419aa-0866-4f90-bfdd-0ab6c22ca6af)

**Comment by erxson** [comment]
Understand. Thanks for the help!

**Comment by bai-xuan** [comment]
请取消注释此代码，很抱歉打扰您。
