### ISSUE TITLE
The method name generation is illegal

### ISSUE THREAD

**Issue by bai-xuan** [erxson/Bruhfuscator#3]
The generated method name is legal and contains'/'.
![image](https://github.com/erxson/Bruhfuscator/assets/38934025/4ee642d0-8fbf-4280-b352-39611fcd1d01)

Find this place through code tracing
![image](https://github.com/erxson/Bruhfuscator/assets/38934025/66d94139-9bc7-473b-8323-0d80ff64e159)

Please delete '$/' as I resolved the issue of illegal method names by deleting them

Additionally, there are issues with this code:

![image](https://github.com/erxson/Bruhfuscator/assets/38934025/978bf37b-8134-4c81-996e-956cc2f5f1d9)

Builder. append (CHARS [random. nextInt (CHARS. length)]);
When random. nextInt (CHARS. length) returns a range of 1-10, a method name that starts with a number is also illegal

![image](https://github.com/erxson/Bruhfuscator/assets/38934025/2e72986b-eafd-426e-8672-8d0fef788622)

**Comment by erxson** [comment]
Thanks!
