### ISSUE TITLE
Testing for randomString

### ISSUE THREAD

**Issue by bai-xuan** [erxson/Bruhfuscator#4]
![image](https://github.com/erxson/Bruhfuscator/assets/38934025/8f6c9eb3-2e3f-4bfe-b016-3c03a61c7556)
![image](https://github.com/erxson/Bruhfuscator/assets/38934025/340f1909-c113-41c1-8fc9-956578d4911f)
You can see that the method name is illegal

Here are my modifications

![image](https://github.com/erxson/Bruhfuscator/assets/38934025/e3944a3e-f274-4394-a4f9-63c9d691c375)

 while (builder.length() < len) {
            int nextInt = random.nextInt(CHARS.length);
            if (builder.length() == 0 && nextInt < 10) {
                continue;
            }
            builder.append(CHARS[nextInt]);
        }

Test the result a thousand times without a string starting with a number

![image](https://github.com/erxson/Bruhfuscator/assets/38934025/9f3a68e6-7985-49a1-85b3-f6e2189d2e62)

I hope you can adopt my method, or if you have any good modifications, I can also learn from it.

**Comment by erxson** [comment]
I advise you to make a pull request, or use ready-made dictionaries like me

**Comment by bai-xuan** [comment]
> I advise you to make a pull request, or use ready-made dictionaries like me

Sorry, I'm not very good at submitting pull requests. I can only point out the problems to you.
