### ISSUE TITLE
[string-encryption] and [goto-shenanigans] configuration items are all true errors.

### ISSUE THREAD

**Issue by bai-xuan** [erxson/Bruhfuscator#5]
![image](https://github.com/erxson/Bruhfuscator/assets/38934025/1af83e5c-c1fd-4663-882a-ea4cd70e148e)

I don't understand why configuring this would cause this error

**Comment by bai-xuan** [comment]
Do you need to hand it over to the original author for resolution? The original author has not submitted the code for six months

**Comment by bai-xuan** [comment]
I think [-noverify arg] should not be used to solve these errors. This is not reasonable. The generated bytecode must always meet the jvm specification.

**Comment by erxson** [comment]
I avoid VerifyError by rolling the configuration

**Comment by erxson** [comment]
Give me your string-encryption configuration

**Comment by bai-xuan** [comment]
![image](https://github.com/erxson/Bruhfuscator/assets/38934025/64288d1a-7d6b-4514-bdbc-f8a4da31b4d0)
![image](https://github.com/erxson/Bruhfuscator/assets/38934025/9d8e8e39-fe43-49fc-8ecf-6614cbe13179)
![image](https://github.com/erxson/Bruhfuscator/assets/38934025/738b66d5-8248-4b6b-bbc5-5579473c4613)

At present, all these configurations are the default ones
=========

I am confusing the application of springboot, and you still need to make the following modifications:

![image](https://github.com/erxson/Bruhfuscator/assets/38934025/77097eed-38b3-4b3b-9440-4b90ed1e7ec5)
![image](https://github.com/erxson/Bruhfuscator/assets/38934025/4fdd9452-cc1e-4303-9945-342424d08a71)
![image](https://github.com/erxson/Bruhfuscator/assets/38934025/09b575cb-42b1-4ca6-9787-1f34b4f17ac8)
![image](https://github.com/erxson/Bruhfuscator/assets/38934025/b179d50c-2632-4481-836b-86984763361b)

**Comment by bai-xuan** [comment]
The above modification is to be compatible with [BOOT-INF\lib] in the springboot application package

**Comment by erxson** [comment]
open pull request

**Comment by bai-xuan** [comment]
![image](https://github.com/erxson/Bruhfuscator/assets/38934025/910ed80d-6063-45c8-958f-488a69585fd4)
springboot packaging configuration

**Comment by erxson** [comment]
try to disable "aggresive" in goto shenanigan

**Comment by bai-xuan** [comment]
I just tried turning off "aggresive" and got the following error
![image](https://github.com/erxson/Bruhfuscator/assets/38934025/3cf91677-a7e7-4445-88cd-4f66e31e02f2)

![image](https://github.com/erxson/Bruhfuscator/assets/38934025/b72201fd-c2fa-4cab-8ec4-4df065d2eff9)

**Comment by erxson** [comment]
I believe in you. You can fix it

**Comment by bai-xuan** [comment]
Brother, I have been researching this problem for two days. I have not solved this problem, so I asked you for help. I hope you can help me. The original author will definitely not be able to help me.

**Comment by erxson** [comment]
I can only help you with moral support

**Comment by bai-xuan** [comment]
This will affect the development of this project. Many people will definitely encounter this problem later and they may give up on the project.

**Comment by erxson** [comment]
![image](https://github.com/erxson/Bruhfuscator/assets/50082485/aede8834-e55a-40eb-a49c-b5802b9c8c74)

**Comment by bai-xuan** [comment]
> ![image](https://user-images.githubusercontent.com/50082485/283752208-aede8834-e55a-40eb-a49c-b5802b9c8c74.png)

Black pictures?

**Comment by erxson** [comment]
![](https://media.tenor.com/lxHAodK6eZIAAAAd/%D0%B4%D0%B0-%D0%BC%D0%BD%D0%B5-%D0%BF%D0%BE%D0%B5%D0%B1%D0%B0%D1%82%D1%8C.gif)
